/////////////////////////////////////////////////////////////////////////////
// RoboHELP® 
// Copyright © 1998-2000 eHelp Corporation.  All rights reserved.

// Version= 4.00

// Warning:  Do not modify this file.  It is generated by RoboHELP® and changes will be overwritten.

var gbBsBlankJsExist = true;